//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upload_WMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnviarDatosUNOEE {
            get {
                return ((bool)(this["EnviarDatosUNOEE"]));
            }
            set {
                this["EnviarDatosUNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string cia_UNOEE {
            get {
                return ((string)(this["cia_UNOEE"]));
            }
            set {
                this["cia_UNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bitPruebas {
            get {
                return ((bool)(this["bitPruebas"]));
            }
            set {
                this["bitPruebas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.211;Initial Catalog=INTWMS;User ID=sa;Password=Sa123456;Int" +
            "egrated Security=False")]
        public string strConexionSQL {
            get {
                return ((string)(this["strConexionSQL"]));
            }
            set {
                this["strConexionSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.54;Initial Catalog=WMS_DisTest;User ID=sa;Password=D1sl1c0r" +
            "3s;Integrated Security=False")]
        public string strConexionSQL_Pruebas {
            get {
                return ((string)(this["strConexionSQL_Pruebas"]));
            }
            set {
                this["strConexionSQL_Pruebas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WSREAL")]
        public string conexion_UNOEE {
            get {
                return ((string)(this["conexion_UNOEE"]));
            }
            set {
                this["conexion_UNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRUEBAS_ATENEA")]
        public string conexion_UNOEE_Pruebas {
            get {
                return ((string)(this["conexion_UNOEE_Pruebas"]));
            }
            set {
                this["conexion_UNOEE_Pruebas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wms.integracion")]
        public string usuario_UNOEE {
            get {
                return ((string)(this["usuario_UNOEE"]));
            }
            set {
                this["usuario_UNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wms2020")]
        public string clave_UNOEE {
            get {
                return ((string)(this["clave_UNOEE"]));
            }
            set {
                this["clave_UNOEE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\PlanosGT\\")]
        public string rutaPlanosGT {
            get {
                return ((string)(this["rutaPlanosGT"]));
            }
            set {
                this["rutaPlanosGT"] = value;
            }
        }
    }
}
